<?php

return [
    [
        'id' => 1,
        'user_id' => 1,
        'hostname' => 'DATA/NET', 
        'password' => word_pass(),
        'org' => 'IDM CORP. NETWORK (IDN)',
        'location' => 'ARMON, NEW YORK, USA',
        'welcome' => 'WELCOME TO IDM CORP. NETWORK',
        'notes' => 'SYSADMIN: ADMIN@DATA/NET',
        'os' => 'SU/DOS V1.10',
        'ip' => random_ip(),
        'is_network' => 1,
        'credits' => 0,
        'created_at' => timestamp("1911-06-16 06:30:00", true)
    ],
    [
        'id' => 2,
        'user_id' => 1,
        'hostname' => 'DATA/COM', 
        'password' => word_pass(),
        'org' => 'INTERNATIONAL DATA MACHINES CORP. (IDM)',
        'location' => 'ARMON, NEW YORK, USA',
        'welcome' => 'WELCOME TO IDM CORP.',
        'notes' => 'SYSADMIN: ADMIN@DATA/COM',
        'os' => 'SU/DOS V1.10',
        'ip' => random_ip(),
        'is_network' => 0,
        'credits' => 5,
        'created_at' => timestamp("1911-06-16 06:30:00", true)
    ],
    [
        'id' => 3,
        'user_id' => 1,
        'hostname' => 'GEC/NET', 
        'password' => word_pass(),
        'org' => 'GEC CORP. NETWORK (GCN)',
        'location' => 'SAN RAMON, CALIFORNIA, USA',
        'welcome' => 'WELCOME TO GEC CORP.',
        'notes' => 'SYSADMIN: ADMIN@GEC/NET',
        'os' => 'SU/DOS V3.0',
        'ip' => random_ip(),
        'is_network' => 1,
        'credits' => 15,
        'created_at' => timestamp("1892-04-30 06:30:00", true)
    ],
    [
        'id' => 4,
        'user_id' => 1,
        'hostname' => 'GEC/COM', 
        'password' => word_pass(),
        'org' => 'GENERAL ENERGY & COMMUNICATION COMPANY (GEC)',
        'location' => 'SAN RAMON, CALIFORNIA, USA',
        'welcome' => 'WELCOME TO GEC CORP.',
        'notes' => 'SYSADMIN: ADMIN@GEC/COM',
        'os' => 'SU/DOS V3.0',
        'ip' => random_ip(),
        'is_network' => 0,
        'credits' => 15,
        'created_at' => timestamp("1892-04-30 06:30:00", true)
    ],
    [
        'id' => 5,
        'user_id' => 1,
        'hostname' => 'DEFCON/NET', 
        'password' => word_pass(),
        'org' => 'DEFCON CORP. NETWORK (DFN)',
        'location' => 'CMOC, COLORADO, USA',
        'welcome' => 'WELCOME TO DEFCON CORP. NETWORK',
        'notes' => 'SYSADMIN: ADMIN@DEFCON/NET',
        'os' => 'SU/DOS V4.0',
        'ip' => random_ip(),
        'is_network' => 1,
        'credits' => 15,
        'created_at' => timestamp("1958-10-30 06:30:00", true)
    ],
    [
        'id' => 6,
        'user_id' => 1,
        'hostname' => 'DEFCON/COM', 
        'password' => word_pass(),
        'org' => 'DEFENSE & CONTROL COMPANY (DFC)',
        'location' => 'LOS ANGELES, CALIFORNIA, USA',
        'welcome' => 'WELCOME TO DEFCON CORP.',
        'notes' => 'SYSADMIN: ADMIN@DEFCON/COM',
        'os' => 'SU/DOS V4.0',
        'ip' => random_ip(),
        'is_network' => 0,
        'credits' => 50,
        'created_at' => timestamp("1958-10-30 06:30:00", true)
    ],
    [
        'id' => 7,
        'user_id' => 1,
        'hostname' => 'DEFCON/MIL', 
        'password' => word_pass(),
        'org' => 'DEFENSE & CONTROL MILITARY COMMAND (DDN)',
        'location' => 'CMOC, COLORADO, USA',
        'welcome' => 'WELCOME TO DEFCON MILITARY COMMAND',
        'notes' => 'SYSADMIN: ADMIN@DEFCON/MIL',
        'os' => 'SU/DOS V4.0',
        'ip' => random_ip(),
        'is_network' => 0,
        'credits' => 100,
        'created_at' => timestamp("1958-10-30 06:30:00", true)
    ],
    [
        'id' => 8,
        'user_id' => 1,
        'hostname' => 'SYSCORP/NET', 
        'password' => word_pass(),
        'org' => 'SYSCORP NETWORK (SCN)',
        'location' => 'NEW YORK, USA',
        'welcome' => 'WELCOME TO THE SYSCORP NETWORK',
        'notes' => 'SYSADMIN: ADMIN@SYSCORP/NET',
        'os' => 'SU/DOS V3.0',
        'ip' => random_ip(),
        'is_network' => 1,
        'credits' => 15,
        'created_at' => timestamp("1950-01-30 06:30:00", true)
    ],
    [
        'id' => 9,
        'user_id' => 1,
        'hostname' => 'SYSCORP/COM', 
        'password' => word_pass(),
        'org' => 'SYSCORP COMPANY (SCC)',
        'location' => 'NEW YORK, USA',
        'welcome' => 'WELCOME TO THE SYSCORP COMPANY',
        'notes' => 'SYSADMIN: ADMIN@SYSCORP/COM',
        'os' => 'SU/DOS V3.0',
        'ip' => random_ip(),
        'is_network' => 0,
        'credits' => 50,
        'created_at' => timestamp("1950-01-30 06:30:00", true)
    ],
    [
        'id' => 10,
        'user_id' => 1,
        'hostname' => 'SYSCORP/EDU', 
        'password' => word_pass(),
        'org' => 'SYSCORP EDUCATION (SCE)',
        'location' => 'LBNL, CALIFORNIA, USA',
        'welcome' => 'WELCOME TO SYSCORP EDUCATION',
        'notes' => 'SYSADMIN: ADMIN@SYSCORP/EDU',
        'os' => 'SU/DOS V1.10',
        'ip' => random_ip(),
        'is_network' => 0,
        'credits' => 5,
        'created_at' => timestamp("1984-01-30 06:30:00", true)
    ],
    [
        'id' => 11,
        'user_id' => 1,
        'hostname' => 'SYSCORP/GOV', 
        'password' => word_pass(),
        'org' => 'SYSCORP SYNDICATE (SCS)',
        'location' => 'WHITE HOUSE, Washington DC, USA',
        'welcome' => 'WELCOME TO THE SYNDICATE.',
        'notes' => 'SYSADMIN: ADMIN@SYSCORP/GOV',
        'os' => 'SU/DOS V3.0',
        'ip' => random_ip(),
        'is_network' => 0,
        'credits' => 75,
        'created_at' => timestamp("1950-01-30 06:30:00", true)
    ],
    [
        'id' => 12,
        'user_id' => 0,
        'hostname' => 'FALLOUT/ORG', 
        'password' => word_pass(),
        'org' => 'THE FALL OUTCASTS CHAOS COMPUTER CLUB (FOCCC)',
        'location' => 'HANNOVER, GERMANY',
        'welcome' => 'WELCOME TO THE OPEN LEGACY-NET, FELLOW OUTCASTS! F*CK (AND HACK) ALL COMPANIES!',
        'notes' => 'SYSADMIN: ADMIN@FALLOUT/ORG',
        'os' => '4.3 BSD VAX-11/780',
        'ip' => random_ip(),
        'is_network' => 0,
        'credits' => 100,
        'created_at' => timestamp("1975-01-30 06:30:00", true)
    ],
];